\section{Discussion} \label{sec:summary}
% Scope of DFC application
The \pkg{digiRhythm} package presents a novel, user-friendly, and accessible tool for researchers in the field of rhythmicity, animal behavior, and beyond. The package offers a versatile approach to assessing rhythmicity based on digital activity records. By leveraging the power of \proglang{R}, it brings robust statistical capabilities and intuitive visualization features into the hands of researchers.

While the current implementation of the \pkg{digiRhythm} package focuses on rhythmicity in farm animals, the underlying principles and methodology can be extended to other organisms, including humans. This opens up exciting avenues for future research in various domains. The unique utilization of harmonic frequencies related to the 24-hour day in the package provides a novel approach for rhythmicity analysis.

The package is designed with flexibility and expansion in mind. The current version allows for the computation of different metrics like DFC, DI, and visualization tools such as actograms. Still, the modular structure of the package enables the incorporation of additional techniques and tools in the future. As the \pkg{digiRhythm} package continues to develop and evolve, we expect it to become an off-the-shelf tool for researchers interested in studying rhythmicity patterns and their implications.

%package enables computation of any activity data
Rhythmicity can be calculated in the \pkg{digiRhythm} package from any type of regularly measured time series data, if the data are prepared in a suitable format. The suitability of the format can be assessed with the  \fct{is\_dgm\_friendly} function. To date, this is purely a computation of activity patterns, resulting in the DFC. This measure has been correlated with physiological functions in previous studies. The computation of rhythmicity allows to gain further insight into an individual's harmonic patterns. Individuals in a good physiological state will present harmonic locomotion patterns, whereas this rhythmicity desynchronizes as a result of physiological events. Simply spoken, an organism will follow the same patterns of locomotion as long as they are in a good physiological and psychological state, whereas these patterns will deviate in the face of dysfunctions. In the past, these rhythmic patterns have been discussed with regard to the psychological state of humans, where  bipolar disorders or depression have been associated with the desynchronization of rhythmic patterns (\cite{sabet2021the}).

%Limitation of DFC computation
However, there is no evidence to whether these activity patterns are intrinsically (such as going to sleep) or extrinsically (such as waking up to an alarm) motivated. Such extrinsic factors could affect rhythmic activity patterns and blur the organisms intrinsic rhythmicity. To date, the package provides the option to exclude extrinsically structured time spans from the analysis. However, in order to increase the understanding of rhythmicity  future studies should investigate how these extrinsic factors affect rhythmicity calculations.
Future research should also address data collection frequencies. Frequency of data collection is of great importance in sensor technology, because sensors are required to be small and expected to run without any sensor based maintenance, such as data reading or charging. This in turn implies that data collection frequencies should be set to a minimum. Although the current package used low data collection frequency in its example data (15 minutes), this time was given by the preset of the sensor data evaluated with this package and has no scientific basis. Future studies should therefore evaluate how low data collection frequencies can be set to compute reliable rhythmicity indicators.

Additionally, seven days of continuous data collection are currently required to compute one DFC value, implying that long data collection intervals are necessary to detect rhythmic patterns. Hereby, the basis for choosing a 7 day window is unclear. Reducing the number of days required to compute one DFC value would make this rhythmicity computation more accessible. Yet, the effect of reducing the intervals has not been investigated. Therefore, we encourage future studies to investigate the impact of reducing the number of days required to compute the DFC.

In addition to the open questions about the data collection frequency and intervals, a comparison to other metrics will be needed in further studies. In the past, other metrics for calculating circadian rhythms have been published. For example, Interdaily Stability (IS), which is mainly used in human research \cite{witting1990alterations}. And the Fourier-Based Approximation with Thresholding (FBAT) was designed to calculate the circadian rhythms of dairy cows \cite{wagner2021detection}. Their database depends on the 24 h day, but none of them use the 24 h within the calculation. The calculation of harmonic frequencies within the DFC calculation, which sets the activity signal in relation to the external 24h day is unique. Therefore, it would be interesting to investigate the correlation between the DFC and rhythmicity computed on data from various computation techniques. In addition to the mentioned metrics (IS and FBAT), \cite{moller2022diurnal} utilized a range of techniques, including set logic, circular cross-correlation, circular clustering, functional enrichment analyses, and least squares regression, on transcriptomic time series data from humans and baboons. Additionally, GPS data of free ranging animals \cite{plaza2022gps} or data of real time positioning systems in a barn \cite{wagner2021detection} could be used to estimate rhythmicity. Comparing the correlations between rhythmicity measures derived from different types of data and between various techniques could be a useful research area. Further, research should evaluate if activity data collected from different sources, such as tri-axial activity data, access of feeding stations or coffee machines, compute similar rhythmicity outputs in the same organism. In addition, further studies usinf simulated data should be conducted, to validate the DFC calculation.

The current package has been developed for farm animals, but the principles of rhythmicity apply for any organism, including humans. Therefore we highly recommend future research to evaluate the \pkg{digiRhythm} package in other species. Many humans nowadays continuously collect activity data with their smart-watches or their phones. A previous review highlighted the potential of such rhythmicity computations in humans \citep{dijk2020novel}. Thus, it would be interesting to implement the \pkg{digiRhythm} package in this domain. F


At the time of writing this paper, the current version (v1.2) of the library does not provide the capability to compute rhythmicity using techniques such as cosinor analysis (\cite{refinetti2016}). However, there is potential for future expansion of the library's functionality to incorporate additional techniques.

Lastly, we welcome contributions to the \pkg{digiRhythm} package. The open-source nature of the package fosters collaboration and continuous improvement. Researchers and developers are encouraged to contribute their codes, methodologies, and data to the project, thereby supporting the scientific community's collaborative spirit. By doing so, we hope to further our understanding of rhythmicity, its implications, and how we can leverage this knowledge for the welfare of animals and humans alike.

